CREATE DATABASE quanlydonhang;

USE quanlydonhang;
CREATE TABLE DV_KHACH (
	Ma_DV INT PRIMARY KEY,
	Ten_DV VARCHAR(50),
	Dia_chi TEXT,
	Dien_thoai VARCHAR(20)
);
USE quanlydonhang;
CREATE TABLE NGUOI_DAT (
  Ma_so_ND INT PRIMARY KEY,
  Ho_ten_ND VARCHAR(50),
  FOREIGN KEY (Ma_so_ND) REFERENCES DV_KHACH(Ma_DV)
);

USE quanlydonhang;
CREATE TABLE NGUOI_NHAN (
  Ma_so_NN INT PRIMARY KEY,
  Ho_ten_NN VARCHAR(50),
  FOREIGN KEY (Ma_so_NN) REFERENCES DV_KHACH(Ma_DV)
);
USE quanlydonhang;
CREATE TABLE HANG(
	Ma_hang INT PRIMARY KEY,
	Ten_hang VARCHAR(50),
	Dv_Tinh TEXT,
	Mo_ta_hang TEXT
);

USE quanlydonhang;
CREATE TABLE NGUOI_GIAO (
  Ma_so_NG INT PRIMARY KEY,
  Ho_ten_NG VARCHAR(50)
);

USE quanlydonhang;
CREATE TABLE NOI_GIAO (
  Ma_so_DDG INT PRIMARY KEY,
  Ten_NG VARCHAR(50)
);
USE quanlydonhang;
CREATE TABLE DS_DON_GIAO_HANG(
	Ma_so_PG INT PRIMARY KEY,
	Ma_NN INT,
	Ma_DDG INT,
	Ma_NG INT,
	Ngay_giao DATE,
	So_luong INT,
	Don_gia FLOAT,
	FOREIGN KEY (Ma_NN) REFERENCES NGUOI_NHAN(Ma_so_NN),
	FOREIGN KEY (Ma_DDG) REFERENCES NOI_GIAO(Ma_so_DDG),
	FOREIGN KEY (Ma_NG) REFERENCES NGUOI_GIAO(Ma_so_NG)
);

USE quanlydonhang;
CREATE TABLE DS_DON_DAT_HANG(
	Ma_so_DH INT PRIMARY KEY,
	Ma_PG INT,
	Ma_ND INT,
	Ma_H INT,
	Ngay_dat DATE,
	So_luong INT,
	FOREIGN KEY (Ma_ND) REFERENCES NGUOI_DAT(Ma_so_ND),
	FOREIGN KEY (Ma_PG) REFERENCES DS_DON_GIAO_HANG(Ma_so_PG),
	FOREIGN KEY (Ma_H) REFERENCES HANG(Ma_hang)
);